### ISSUE TITLE
test KubeRay candidate v1.0.0-rc.0

### ISSUE THREAD

**Issue by jbusche** [opendatahub-io/distributed-workloads#135]
A new version of KubeRay Operator is out.  https://github.com/ray-project/kuberay/tree/v1.0.0-rc.0/
Which needs testing...

**Comment by jbusche** [comment]
I've created a branch to test it:
https://github.com/jbusche/distributed-workloads/tree/kuberay-100-rc.0

and have applied this kfdef in my cluster for testing:
```
apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  name: codeflare-stack
  namespace: opendatahub
spec:
  applications:
  # CodeFlare
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: codeflare-stack
    name: codeflare-stack
  # KubeRay
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: ray/operator
    name: ray-operator
  repos:
    # ODH Core component manifests
  - name: manifests
    #uri: https://github.com/opendatahub-io/distributed-workloads/tarball/main
    uri: https://github.com/jbusche/distributed-workloads/tarball/kuberay-100-rc.0
```

When applied, the operator looks good:
```
oc describe pod kuberay-operator-7d768cd4b8-9gvnc |grep Image:
    Image:         quay.io/kuberay/operator:v1.0.0-rc.0
```
