### ISSUE TITLE
Tweak of E2E Notebook tests to improve performance

### ISSUE THREAD

**Issue by jbusche** [opendatahub-io/distributed-workloads#41]
changes:
 vi operator-tests/opendatahub-kubeflow/tests/resources/custom-nb-small.yaml
```
        resources:
          limits:
            cpu: "2"
            memory: 8Gi  --> to 3Gi
          requests:
            cpu: "1"
            memory: 8Gi  --> to 3Gi
```
2.  vi operator-tests/opendatahub-kubeflow/tests/resources/mnist_mcad_mini.ipynb
```
gpu=0, cpu=1, memMB=8000
to
gpu=0, cpu=3, memMB=4000
```
3.  vi operator-tests/opendatahub-kubeflow/tests/resources/mnist_ray_mini.ipynb
```
min_cpus=1, max_cpus=1, min_memory=4, max_memory=4, gpu=0
to
min_cpus=2, max_cpus=2, min_memory=4, max_memory=4, gpu=0
```
With these changes, the time to run the test went from (Note, this is with pre-cached images on the worker nodes)

With above changes:  ./run.sh took 697 seconds

Without above changes: It's Really slow for mnist_mcad_mini.ipynb and can't complete within the 1200 second timeout,
```
./run.sh took 1247 seconds
```
and I'm pretty sure the ray job wouldn't be able to start due to memory pressure.
