### ISSUE TITLE
Create a Ray kfdef folder to test out the 0.6.0-rc.1 candidate

### ISSUE THREAD

**Issue by jbusche** [opendatahub-io/distributed-workloads#65]
The RC 1 candidate of kuberay 0.6.0 is available https://ray-distributed.slack.com/archives/C02GFQ82JPM/p1689895388577229

I'd like to try a test PR of v0.6.0-rc.1 to make sure that there are no issues with CodeFlare

**Comment by jbusche** [comment]
Created a branch https://github.com/jbusche/distributed-workloads/tree/kuberay-060-rc1 for testing. It's looking good so far:
```
oc get pods -n default                                                                                                                                                 api.jimmed.cp.fyre.ibm.com: Mon Jul 24 12:58:21 2023

NAME                                           READY   STATUS    RESTARTS   AGE
mnisttest-head-4pxqr                           1/1     Running   0          5m23s
mnisttest-worker-small-group-mnisttest-5mkht   1/1     Running   0          5m23s
mnisttest-worker-small-group-mnisttest-9mmqj   1/1     Running   0          5m23s
```
and oc describe pod kuberay-operator-d447445c6-9t2mk |grep Image
```
    Image:         docker.io/kuberay/operator:v0.6.0-rc.1
    Image ID:      docker.io/kuberay/operator@sha256:ba19a29c543c1adf23d52fd355fd2772554c9fdebef48dd4b6a3a4ac29b6ce56
```
and
```
job.status()
AppStatus:
  msg: !!python/object/apply:ray.dashboard.modules.job.common.JobStatus
  - SUCCEEDED
  num_restarts: -1
```

**Comment by jbusche** [comment]
Applied this kfdef for testing:
```
apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  name: codeflare-stack
  namespace: opendatahub
spec:
  applications:
  # CodeFlare
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: codeflare-stack
    name: codeflare-stack
  # KubeRay
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: ray/operator
    name: ray-operator
  repos:
    # ODH Core component manifests
  - name: manifests
    #uri: https://github.com/opendatahub-io/distributed-workloads/tarball/main
    uri: https://github.com/jbusche/distributed-workloads/tarball/kuberay-060-rc1
```
